### ISSUE TITLE
booting thru fastboot error

### ISSUE THREAD

**Issue by KamboSoup** [Wishmasterflo/ofox_salami#3]
tried booting IMG file thru fastboot but met with 

downloading "boot.img"
OKAY [ 2.440s]
booting...
FAILED (status read failed (Too many links))
finished. total time: 2.586s

phone just boots to OS

**Comment by Wishmasterflo** [comment]
That seems to be some issue on your side. Perhaps try with some other Version of adb/fastboot drivers. Otherwise you can adb sideload the Orangefox.zip file from a custom recovery, that should work.

**Comment by KamboSoup** [comment]
I tried a couple different adb/fastboot drivers. I still get either the same error message or this error message 'Failed to load/authenticate boot image: Bad Buffer Size'.
I have root on my phone already, is it possible to flash OrangeFox thru Magisk?

**Comment by Wishmasterflo** [comment]
Ah got it.
I guess on Oneplus 11 you can not use fastboot boot to boot into the recovery. You need to flash it or sideload the orangefox.zip file from a custom recovery.
